- project:
    name: ceph-container-nightly
    os:
      - centos7
      - xenial
    ceph-version:
      - jewel
      - luminous
    test:
      - cluster
      - bluestore_osds_container
      - filestore_osds_container
    exclude:
       - ceph-version: jewel
         test: bluestore_osds_container
    jobs:
        - 'ceph-container-nightly-ceph_ansible-{ceph-version}-{os}-{test}'

- job-template:
    name: 'ceph-container-nightly-ceph_ansible-{ceph-version}-{os}-{test}'
    node: vagrant&&libvirt&&centos7
    concurrent: true
    defaults: global
    display-name: 'ceph-container: Nightly tests [ceph_ansible-{ceph-version}-{os}-{test}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-container
      - build-discarder:
          days-to-keep: -1
          num-to-keep: -1
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1

    parameters:
      - string:
          name: BRANCH
          description: "A ceph-container branch to test"
          default: master

    triggers:
      - timed: '@daily'

    scm:
      - git:
          url: https://github.com/ceph/ceph-container.git
          branches:
            - ${{BRANCH}}
          browser: auto
          timeout: 20

    builders:
      - inject:
          properties-content: |
            SCENARIO=ceph_ansible-{ceph-version}-{os}-{test}
            NIGHTLY=TRUE
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell: !include-raw ../../build/teardown
